name: gather
description: Gym Buddy Matching App - GTHR
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 📦 Core Packages
  go_router: ^9.0.3
  dio: ^5.3.3
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  uuid: ^4.0.0
  google_fonts: ^6.1.0
  lottie: ^2.6.0

  # 📦 Firebase & Chat
  firebase_core: ^2.12.0
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.8.3
  firebase_messaging: ^14.7.3
  flutter_local_notifications: ^15.1.0

  # 📦 Forms & Validation
  flutter_form_builder: ^9.1.1
  form_field_validator: ^1.1.0

  # 📦 Image Handling
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  # 📦 Dev Tools
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/mock_data/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
